using System;using System.Collections.Concurrent;using System.Collections.Generic;using System.IO;using System.IO.Compression;using System.Linq;using System.Net;using System.Net.NetworkInformation;using System.Net.Sockets;using System.Security.Cryptography;using System.Text;using System.Threading;using System.Threading.Tasks;using Microsoft.Extensions.Logging;using PhotoBooth.Core.Models;using PhotoBooth.Core.Services;using PhotoBooth.Shared;
namespace PhotoBooth.Infrastructure.Services
{
 public sealed class LocalShareService:ILocalShareService,IDisposable
 {
  sealed class ShareEntry { public string ZipPath;public string DownloadName;public DateTime ExpiresAtUtc; }
  readonly ApplicationOptions options;readonly ISettingsService settings;readonly ILogger<LocalShareService> log;readonly ConcurrentDictionary<string,ShareEntry> shares=new ConcurrentDictionary<string,ShareEntry>();readonly CancellationTokenSource stop=new CancellationTokenSource();readonly SemaphoreSlim startGate=new SemaphoreSlim(1,1);TcpListener listener;Task acceptLoop;string baseUrl;
  public LocalShareService(ApplicationOptions options,ISettingsService settings,ILogger<LocalShareService> logger){this.options=options;this.settings=settings;log=logger;CleanupOldArchives();}
  public bool IsRunning=>listener!=null;public string BaseUrl=>baseUrl;
  public async Task StartAsync(CancellationToken token)
  {
   var configured=await settings.GetAsync(token);if(configured!=null&&!configured.LocalShareEnabled)throw new InvalidOperationException("Local Share is disabled in Admin settings.");await EnsureStarted(token);
  }
  public async Task<LocalShareTicket> CreateAsync(Guid sessionId,string captureId,IReadOnlyList<string> files,CancellationToken token)
  {
   if(string.IsNullOrWhiteSpace(captureId))throw new ArgumentException("Capture ID is required.",nameof(captureId));await StartAsync(token);var valid=(files??new string[0]).Where(x=>!string.IsNullOrWhiteSpace(x)&&File.Exists(x)).Distinct(StringComparer.OrdinalIgnoreCase).ToList();if(valid.Count==0)throw new InvalidOperationException("No capture files are available for sharing.");var ticketId=Guid.NewGuid().ToString("N");var folder=sessionId.ToString("N")+"."+captureId;var shareDir=Path.Combine(options.DataDirectory,"LocalShare");Directory.CreateDirectory(shareDir);var zip=Path.Combine(shareDir,folder+".zip");await Task.Run(()=>CreateArchive(zip,folder,valid),token);var key=NewToken();var expires=DateTime.UtcNow.AddMinutes(30);shares[key]=new ShareEntry{ZipPath=zip,DownloadName=folder+".zip",ExpiresAtUtc=expires};var url=new Uri(baseUrl+"download/"+key);log.LogInformation("Local Share {ShareId} created for session {SessionId}, capture {CaptureId}: {Url}",ticketId,sessionId,captureId,url);return new LocalShareTicket{Id=ticketId,SessionId=sessionId,CaptureId=captureId,DownloadUrl=url,ZipPath=zip,ExpiresAtUtc=expires};
  }
  async Task EnsureStarted(CancellationToken token)
  {
   if(listener!=null)return;await startGate.WaitAsync(token);try{if(listener!=null)return;var address=FindLanAddress();if(address==null)throw new InvalidOperationException("No active LAN IPv4 address was found. Connect both devices to the same Wi-Fi.");for(var port=8787;port<=8797;port++){try{listener=new TcpListener(IPAddress.Any,port);listener.Start();baseUrl="http://"+address+":"+port+"/";break;}catch(SocketException){listener=null;}}if(listener==null)throw new InvalidOperationException("Local Share could not open ports 8787-8797.");acceptLoop=Task.Run(()=>AcceptLoop(stop.Token));log.LogInformation("Local Share listening at {BaseUrl}",baseUrl);}finally{startGate.Release();}
  }
  async Task AcceptLoop(CancellationToken token)
  {
   while(!token.IsCancellationRequested)try{var client=await listener.AcceptTcpClientAsync();_ = Task.Run(()=>Handle(client,token));}catch(ObjectDisposedException){break;}catch(Exception e){if(!token.IsCancellationRequested)log.LogWarning(e,"Local Share accept failed");}
  }
  async Task Handle(TcpClient client,CancellationToken token)
  {
   using(client)using(var stream=client.GetStream())try{client.ReceiveTimeout=10000;client.SendTimeout=30000;var reader=new StreamReader(stream,Encoding.ASCII,false,1024,true);var request=await reader.ReadLineAsync();if(string.IsNullOrWhiteSpace(request)){await Error(stream,400,"Bad Request",token);return;}string line;do{line=await reader.ReadLineAsync();}while(!string.IsNullOrEmpty(line));var parts=request.Split(' ');if(parts.Length<2||parts[0]!="GET"){await Error(stream,405,"Method Not Allowed",token);return;}var path=parts[1].Split('?')[0];if(path=="/"||path=="/health"){await Text(stream,"PhotoBooth Local Share is ready.",token);return;}const string prefix="/download/";if(!path.StartsWith(prefix,StringComparison.Ordinal)){await Error(stream,404,"Not Found",token);return;}var key=path.Substring(prefix.Length);if(!shares.TryGetValue(key,out var item)||item.ExpiresAtUtc<=DateTime.UtcNow||!File.Exists(item.ZipPath)){shares.TryRemove(key,out _);await Error(stream,410,"Link expired",token);return;}var length=new FileInfo(item.ZipPath).Length;var header="HTTP/1.1 200 OK\r\nContent-Type: application/zip\r\nContent-Length: "+length+"\r\nContent-Disposition: attachment; filename=\""+item.DownloadName+"\"\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n";var bytes=Encoding.ASCII.GetBytes(header);await stream.WriteAsync(bytes,0,bytes.Length,token);using(var file=File.OpenRead(item.ZipPath))await file.CopyToAsync(stream,81920,token);}catch(Exception e){log.LogDebug(e,"Local Share request ended");}
  }
  static async Task Text(Stream stream,string message,CancellationToken token){var body=Encoding.UTF8.GetBytes(message);var head=Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: "+body.Length+"\r\nConnection: close\r\n\r\n");await stream.WriteAsync(head,0,head.Length,token);await stream.WriteAsync(body,0,body.Length,token);}
  static async Task Error(Stream stream,int code,string message,CancellationToken token){var body=Encoding.UTF8.GetBytes(message);var head=Encoding.ASCII.GetBytes("HTTP/1.1 "+code+" "+message+"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: "+body.Length+"\r\nConnection: close\r\n\r\n");await stream.WriteAsync(head,0,head.Length,token);await stream.WriteAsync(body,0,body.Length,token);}
  internal static void CreateArchive(string zip,string root,IReadOnlyList<string> files){var temp=zip+".tmp";if(File.Exists(temp))File.Delete(temp);var expected=new Dictionary<string,string>(StringComparer.Ordinal);using(var output=File.Create(temp))using(var archive=new ZipArchive(output,ZipArchiveMode.Create)){var used=new HashSet<string>(StringComparer.OrdinalIgnoreCase);for(var i=0;i<files.Count;i++){var name=Path.GetFileName(files[i]);if(!used.Add(name)){name=(i+1).ToString("D2")+"-"+name;used.Add(name);}var fullName=root+"/"+name;expected[fullName]=Hash(files[i]);var entry=archive.CreateEntry(fullName,CompressionLevel.Optimal);using(var source=File.OpenRead(files[i]))using(var target=entry.Open())source.CopyTo(target);}}using(var archive=ZipFile.OpenRead(temp)){if(archive.Entries.Count!=expected.Count)throw new InvalidDataException("Share archive entry count is invalid.");foreach(var item in expected){var entry=archive.GetEntry(item.Key);if(entry==null)throw new InvalidDataException("Share archive is missing "+item.Key);using(var stream=entry.Open())if(!string.Equals(Hash(stream),item.Value,StringComparison.Ordinal))throw new InvalidDataException("Share archive changed bytes for "+item.Key);}}if(File.Exists(zip))File.Delete(zip);File.Move(temp,zip);}
  static string Hash(string path){using(var stream=File.OpenRead(path))return Hash(stream);}static string Hash(Stream stream){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(stream)).Replace("-",string.Empty);}
  static string NewToken(){var bytes=new byte[18];using(var rng=RandomNumberGenerator.Create())rng.GetBytes(bytes);return Convert.ToBase64String(bytes).TrimEnd('=').Replace('+','-').Replace('/','_');}
  static IPAddress FindLanAddress(){return NetworkInterface.GetAllNetworkInterfaces().Where(x=>x.OperationalStatus==OperationalStatus.Up&&x.NetworkInterfaceType!=NetworkInterfaceType.Loopback).SelectMany(x=>x.GetIPProperties().UnicastAddresses.Select(a=>new{Address=a.Address,Gateway=x.GetIPProperties().GatewayAddresses.Any(g=>g.Address.AddressFamily==AddressFamily.InterNetwork&&!g.Address.Equals(IPAddress.Any))})).Where(x=>x.Address.AddressFamily==AddressFamily.InterNetwork&&!IPAddress.IsLoopback(x.Address)&&!x.Address.ToString().StartsWith("169.254.")).OrderByDescending(x=>x.Gateway).Select(x=>x.Address).FirstOrDefault();}
  void CleanupOldArchives(){try{var dir=Path.Combine(options.DataDirectory,"LocalShare");if(!Directory.Exists(dir))return;foreach(var file in Directory.EnumerateFiles(dir,"*.zip"))if(File.GetLastWriteTimeUtc(file)<DateTime.UtcNow.AddHours(-2))File.Delete(file);}catch(Exception e){log.LogDebug(e,"Local Share archive cleanup failed");}}
  public void Dispose(){stop.Cancel();try{listener?.Stop();}catch{}try{acceptLoop?.Wait(1000);}catch{}startGate.Dispose();stop.Dispose();}
 }
}
