using System;using System.Collections.Concurrent;using System.Collections.Generic;using System.Drawing;using System.Drawing.Drawing2D;using System.Drawing.Imaging;using System.IO;using System.Linq;using System.Net;using System.Net.NetworkInformation;using System.Net.Sockets;using System.Security.Cryptography;using System.Text;using System.Threading;using System.Threading.Tasks;using Accord.Video.FFMPEG;using Microsoft.Extensions.Logging;using PhotoBooth.Core.Models;using PhotoBooth.Core.Services;using PhotoBooth.Shared;
namespace PhotoBooth.Infrastructure.Services
{
 public sealed class LocalShareService:ILocalShareService,IDisposable
 {
  internal sealed class ShareAsset{public string Id;public string FilePath;public string DownloadName;public string MimeType;public string Label;public string ThumbnailPath;}
  sealed class ShareEntry{public IReadOnlyList<ShareAsset> Assets;public DateTime ExpiresAtUtc;}
  readonly ApplicationOptions options;readonly ISettingsService settings;readonly ILogger<LocalShareService> log;readonly ConcurrentDictionary<string,ShareEntry> shares=new ConcurrentDictionary<string,ShareEntry>();readonly CancellationTokenSource stop=new CancellationTokenSource();readonly SemaphoreSlim startGate=new SemaphoreSlim(1,1);TcpListener listener;Task acceptLoop;string baseUrl;
  public LocalShareService(ApplicationOptions options,ISettingsService settings,ILogger<LocalShareService> logger){this.options=options;this.settings=settings;log=logger;CleanupOldShareData();}
  public bool IsRunning=>listener!=null;public string BaseUrl=>baseUrl;
  public async Task StartAsync(CancellationToken token){var configured=await settings.GetAsync(token);if(configured!=null&&!configured.LocalShareEnabled)throw new InvalidOperationException("Local Share is disabled in Admin settings.");await EnsureStarted(token);}
  public async Task<LocalShareTicket> CreateAsync(Guid sessionId,string captureId,IReadOnlyList<string> files,CancellationToken token)
  {
   if(string.IsNullOrWhiteSpace(captureId))throw new ArgumentException("Capture ID is required.",nameof(captureId));await StartAsync(token);var valid=(files??new string[0]).Where(x=>!string.IsNullOrWhiteSpace(x)&&File.Exists(x)).Select(Path.GetFullPath).Distinct(StringComparer.OrdinalIgnoreCase).ToList();if(valid.Count==0)throw new InvalidOperationException("No capture files are available for sharing.");
   var ticketId=Guid.NewGuid().ToString("N");var key=NewToken();var thumbnailDirectory=Path.Combine(options.DataDirectory,"LocalShare",key);Directory.CreateDirectory(thumbnailDirectory);var assets=await Task.Run(()=>CreateAssets(valid,thumbnailDirectory,token),token);var expires=DateTime.UtcNow.AddMinutes(30);shares[key]=new ShareEntry{Assets=assets,ExpiresAtUtc=expires};var url=new Uri(baseUrl+"share/"+key);log.LogInformation("Local Share gallery {ShareId} created for session {SessionId}, capture {CaptureId}: {Url}",ticketId,sessionId,captureId,url);return new LocalShareTicket{Id=ticketId,SessionId=sessionId,CaptureId=captureId,DownloadUrl=url,ExpiresAtUtc=expires};
  }
  internal static IReadOnlyList<ShareAsset> CreateAssets(IReadOnlyList<string> files,string thumbnailDirectory,CancellationToken token)
  {
   var result=new List<ShareAsset>();var picture=0;var gif=0;var video=0;
   foreach(var path in files){token.ThrowIfCancellationRequested();var mime=MimeType(path);string label;if(mime=="video/mp4")label="Video "+(++video);else if(mime=="image/gif")label="Ảnh động "+(++gif);else label="Ảnh "+(++picture);var id=Guid.NewGuid().ToString("N");var thumbnail=Path.Combine(thumbnailDirectory,id+".jpg");try{CreateThumbnail(path,mime,thumbnail);}catch{CreatePlaceholder(thumbnail,mime=="video/mp4"?"VIDEO":"ẢNH");}result.Add(new ShareAsset{Id=id,FilePath=path,DownloadName=SafeDownloadName(Path.GetFileName(path)),MimeType=mime,Label=label,ThumbnailPath=thumbnail});}return result;
  }
  async Task EnsureStarted(CancellationToken token)
  {
   if(listener!=null)return;await startGate.WaitAsync(token);try{if(listener!=null)return;var address=FindLanAddress();if(address==null)throw new InvalidOperationException("No active LAN IPv4 address was found. Connect both devices to the same Wi-Fi.");for(var port=8787;port<=8797;port++){try{listener=new TcpListener(IPAddress.Any,port);listener.Start();baseUrl="http://"+address+":"+port+"/";break;}catch(SocketException){listener=null;}}if(listener==null)throw new InvalidOperationException("Local Share could not open ports 8787-8797.");acceptLoop=Task.Run(()=>AcceptLoop(stop.Token));log.LogInformation("Local Share listening at {BaseUrl}",baseUrl);}finally{startGate.Release();}
  }
  async Task AcceptLoop(CancellationToken token){while(!token.IsCancellationRequested)try{var client=await listener.AcceptTcpClientAsync();_=Task.Run(()=>Handle(client,token));}catch(ObjectDisposedException){break;}catch(Exception e){if(!token.IsCancellationRequested)log.LogWarning(e,"Local Share accept failed");}}
  async Task Handle(TcpClient client,CancellationToken token)
  {
   using(client)using(var stream=client.GetStream())try{client.ReceiveTimeout=10000;client.SendTimeout=30000;var reader=new StreamReader(stream,Encoding.ASCII,false,1024,true);var request=await reader.ReadLineAsync();if(string.IsNullOrWhiteSpace(request)){await Error(stream,400,"Bad Request",token);return;}string line;do{line=await reader.ReadLineAsync();}while(!string.IsNullOrEmpty(line));var parts=request.Split(' ');if(parts.Length<2||parts[0]!="GET"){await Error(stream,405,"Method Not Allowed",token);return;}var path=Uri.UnescapeDataString(parts[1].Split('?')[0]);if(path=="/"||path=="/health"){await Text(stream,"PhotoBooth Local Share is ready.",token);return;}await Route(stream,path,token);}catch(Exception e){log.LogDebug(e,"Local Share request ended");}
  }
  async Task Route(Stream stream,string path,CancellationToken token)
  {
   var segments=path.Trim('/').Split('/');if(segments.Length<2||segments[0]!="share"){await Error(stream,404,"Not Found",token);return;}var key=segments[1];ShareEntry entry;if(!shares.TryGetValue(key,out entry)||entry.ExpiresAtUtc<=DateTime.UtcNow){shares.TryRemove(key,out entry);await Error(stream,410,"Link expired",token);return;}if(segments.Length==2){await Html(stream,BuildGalleryHtml(key,entry.Assets),token);return;}if(segments.Length!=4){await Error(stream,404,"Not Found",token);return;}var asset=entry.Assets.FirstOrDefault(x=>string.Equals(x.Id,segments[3],StringComparison.Ordinal));if(asset==null){await Error(stream,404,"Not Found",token);return;}if(segments[2]=="thumbnail")await FileResponse(stream,asset.ThumbnailPath,"image/jpeg",null,true,token);else if(segments[2]=="download")await FileResponse(stream,asset.FilePath,asset.MimeType,asset.DownloadName,false,token);else await Error(stream,404,"Not Found",token);
  }
  internal static string BuildGalleryHtml(string key,IReadOnlyList<ShareAsset> assets)
  {
   var cards=new StringBuilder();foreach(var asset in assets){var id=WebUtility.HtmlEncode(asset.Id);cards.Append("<article class=card><img loading=lazy src=\"/share/").Append(key).Append("/thumbnail/").Append(id).Append("\" alt=\"\"><div class=label>").Append(WebUtility.HtmlEncode(asset.Label)).Append("</div><button class=download data-id=\"").Append(id).Append("\">Tải về</button></article>");}var ids=string.Join(",",assets.Select(x=>"'"+x.Id+"'"));
   return "<!doctype html><html lang=vi><head><meta charset=utf-8><meta name=viewport content=\"width=device-width,initial-scale=1\"><title>Ảnh của bạn</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f5f7;color:#171717;font-family:system-ui,-apple-system,sans-serif;padding:24px 16px 104px}h1{text-align:center;font-size:28px;margin:4px 0 24px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;max-width:760px;margin:auto}.card{background:#fff;border-radius:14px;padding:10px;box-shadow:0 2px 12px #0001}.card img{display:block;width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:10px;background:#ddd}.label{font-weight:650;margin:10px 2px 8px}.download,.all{border:0;border-radius:10px;background:#171717;color:white;font-size:16px;font-weight:650;padding:12px;width:100%}.download.done{background:#666}.bar{position:fixed;z-index:5;left:0;right:0;bottom:0;padding:12px 16px calc(12px + env(safe-area-inset-bottom));background:#fffffff2;box-shadow:0 -3px 18px #0002}.all{display:block;max-width:760px;margin:auto;padding:15px;background:#146cff}.hint{text-align:center;font-size:13px;margin:7px 0 0;color:#555}@media(min-width:680px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}</style></head><body><h1>Ảnh của bạn</h1><main class=grid>"+cards+"</main><footer class=bar><button id=all class=all>Tải tất cả</button><p id=hint class=hint></p></footer><script>const token='"+key+"',ids=["+ids+"],store='photobooth.downloaded.'+token;let done=new Set(JSON.parse(localStorage.getItem(store)||'[]'));const save=()=>localStorage.setItem(store,JSON.stringify([...done]));function mark(id){done.add(id);save();const b=document.querySelector('[data-id=\"'+id+'\"]');if(b){b.classList.add('done');b.textContent='Tải lại';}}function start(id){const a=document.createElement('a');a.href='/share/'+token+'/download/'+id;a.download='';document.body.appendChild(a);a.click();a.remove();mark(id)}document.querySelectorAll('.download').forEach(b=>{if(done.has(b.dataset.id))mark(b.dataset.id);b.onclick=()=>start(b.dataset.id)});document.getElementById('all').onclick=async()=>{const pending=ids.filter(id=>!done.has(id)),hint=document.getElementById('hint');if(!pending.length){hint.textContent='Bạn đã tải tất cả ảnh và video.';return}hint.textContent='Đang tải '+pending.length+' tệp. Nếu được hỏi, hãy cho phép tải nhiều tệp.';for(const id of pending){start(id);await new Promise(r=>setTimeout(r,1200))}hint.textContent='Đã gửi tất cả tệp tới trình duyệt.'};</script></body></html>";
  }
  static void CreateThumbnail(string path,string mime,string destination)
  {
   if(mime=="video/mp4")using(var reader=new VideoFileReader()){reader.Open(path);using(var frame=reader.ReadVideoFrame()){if(frame==null)throw new InvalidDataException("Video has no thumbnail frame.");SaveThumbnail(frame,destination);}}else using(var image=Image.FromFile(path))SaveThumbnail(image,destination);
  }
  static void SaveThumbnail(Image source,string destination)
  {
   const int maximum=480;var scale=Math.Min(1d,Math.Min(maximum/(double)source.Width,maximum/(double)source.Height));var width=Math.Max(1,(int)Math.Round(source.Width*scale));var height=Math.Max(1,(int)Math.Round(source.Height*scale));using(var bitmap=new Bitmap(width,height,PixelFormat.Format24bppRgb)){using(var graphics=Graphics.FromImage(bitmap)){graphics.Clear(Color.White);graphics.InterpolationMode=InterpolationMode.HighQualityBicubic;graphics.DrawImage(source,0,0,width,height);}var codec=ImageCodecInfo.GetImageEncoders().First(x=>x.FormatID==ImageFormat.Jpeg.Guid);using(var parameters=new EncoderParameters(1)){parameters.Param[0]=new EncoderParameter(System.Drawing.Imaging.Encoder.Quality,78L);bitmap.Save(destination,codec,parameters);}}
  }
  static void CreatePlaceholder(string destination,string text){using(var bitmap=new Bitmap(480,320))using(var graphics=Graphics.FromImage(bitmap))using(var font=new Font("Segoe UI",28,FontStyle.Bold))using(var brush=new SolidBrush(Color.White)){graphics.Clear(Color.FromArgb(38,38,42));var size=graphics.MeasureString(text,font);graphics.DrawString(text,font,brush,(bitmap.Width-size.Width)/2,(bitmap.Height-size.Height)/2);bitmap.Save(destination,ImageFormat.Jpeg);}}
  static async Task FileResponse(Stream stream,string path,string mime,string downloadName,bool cache,CancellationToken token){if(!File.Exists(path)){await Error(stream,404,"Not Found",token);return;}var length=new FileInfo(path).Length;var disposition=downloadName==null?string.Empty:"Content-Disposition: attachment; filename=\""+downloadName.Replace("\"",string.Empty)+"\"\r\n";var header="HTTP/1.1 200 OK\r\nContent-Type: "+mime+"\r\nContent-Length: "+length+"\r\n"+disposition+"Cache-Control: "+(cache?"private, max-age=1800":"no-store")+"\r\nX-Content-Type-Options: nosniff\r\nConnection: close\r\n\r\n";var bytes=Encoding.ASCII.GetBytes(header);await stream.WriteAsync(bytes,0,bytes.Length,token);using(var file=File.OpenRead(path))await file.CopyToAsync(stream,81920,token);}
  static async Task Html(Stream stream,string value,CancellationToken token){var body=Encoding.UTF8.GetBytes(value);var header=Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: "+body.Length+"\r\nCache-Control: no-store\r\nContent-Security-Policy: default-src 'self'; img-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; frame-ancestors 'none'\r\nX-Frame-Options: DENY\r\nX-Content-Type-Options: nosniff\r\nConnection: close\r\n\r\n");await stream.WriteAsync(header,0,header.Length,token);await stream.WriteAsync(body,0,body.Length,token);}
  static async Task Text(Stream stream,string message,CancellationToken token){var body=Encoding.UTF8.GetBytes(message);var head=Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: "+body.Length+"\r\nConnection: close\r\n\r\n");await stream.WriteAsync(head,0,head.Length,token);await stream.WriteAsync(body,0,body.Length,token);}
  static async Task Error(Stream stream,int code,string message,CancellationToken token){var body=Encoding.UTF8.GetBytes(message);var head=Encoding.ASCII.GetBytes("HTTP/1.1 "+code+" "+message+"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: "+body.Length+"\r\nConnection: close\r\n\r\n");await stream.WriteAsync(head,0,head.Length,token);await stream.WriteAsync(body,0,body.Length,token);}
  static string MimeType(string path){switch(Path.GetExtension(path).ToLowerInvariant()){case ".jpg":case ".jpeg":return "image/jpeg";case ".png":return "image/png";case ".gif":return "image/gif";case ".mp4":return "video/mp4";default:return "application/octet-stream";}}
  static string SafeDownloadName(string name){var value=new string((name??"download").Select(c=>c<=127&&c!='"'&&c!='\r'&&c!='\n'?c:'_').ToArray());return string.IsNullOrWhiteSpace(value)?"download":value;}
  static string NewToken(){var bytes=new byte[18];using(var rng=RandomNumberGenerator.Create())rng.GetBytes(bytes);return Convert.ToBase64String(bytes).TrimEnd('=').Replace('+','-').Replace('/','_');}
  static IPAddress FindLanAddress(){return NetworkInterface.GetAllNetworkInterfaces().Where(x=>x.OperationalStatus==OperationalStatus.Up&&x.NetworkInterfaceType!=NetworkInterfaceType.Loopback).SelectMany(x=>x.GetIPProperties().UnicastAddresses.Select(a=>new{Address=a.Address,Gateway=x.GetIPProperties().GatewayAddresses.Any(g=>g.Address.AddressFamily==AddressFamily.InterNetwork&&!g.Address.Equals(IPAddress.Any))})).Where(x=>x.Address.AddressFamily==AddressFamily.InterNetwork&&!IPAddress.IsLoopback(x.Address)&&!x.Address.ToString().StartsWith("169.254.")).OrderByDescending(x=>x.Gateway).Select(x=>x.Address).FirstOrDefault();}
  void CleanupOldShareData(){try{var directory=Path.Combine(options.DataDirectory,"LocalShare");if(!Directory.Exists(directory))return;foreach(var file in Directory.EnumerateFiles(directory,"*.zip"))if(File.GetLastWriteTimeUtc(file)<DateTime.UtcNow.AddHours(-2))File.Delete(file);foreach(var folder in Directory.EnumerateDirectories(directory))if(Directory.GetLastWriteTimeUtc(folder)<DateTime.UtcNow.AddHours(-2))Directory.Delete(folder,true);}catch(Exception e){log.LogDebug(e,"Local Share cleanup failed");}}
  public void Dispose(){stop.Cancel();try{listener?.Stop();}catch{}try{acceptLoop?.Wait(1000);}catch{}startGate.Dispose();stop.Dispose();}
 }
}
