<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net48</TargetFramework><LangVersion>latest</LangVersion></PropertyGroup><ItemGroup><ProjectReference Include="..\PhotoBooth.Core\PhotoBooth.Core.csproj" /><ProjectReference Include="..\PhotoBooth.Shared\PhotoBooth.Shared.csproj" /><PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" /><Reference Include="System.Drawing" /><Reference Include="System.Management" /><Reference Include="System.Runtime.Serialization" /></ItemGroup></Project>
