<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net48</TargetFramework><LangVersion>latest</LangVersion><UseWPF>true</UseWPF><PlatformTarget>x86</PlatformTarget><Prefer32Bit>true</Prefer32Bit><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType><StartupObject>PhotoBooth.Admin.UI.App</StartupObject><Version>1.1.0</Version></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PhotoBooth.Core\PhotoBooth.Core.csproj" />
    <ProjectReference Include="..\PhotoBooth.Infrastructure\PhotoBooth.Infrastructure.csproj" />
    <ProjectReference Include="..\PhotoBooth.Shared\PhotoBooth.Shared.csproj" />
    <ProjectReference Include="..\PhotoBooth.Customer.UI\PhotoBooth.Customer.UI.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
    <PackageReference Include="Velopack" Version="1.2.0" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\PhotoBooth.Native\Canon\EDSDK.dll" Link="EDSDK.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\PhotoBooth.Native\Canon\EdsImage.dll" Link="EdsImage.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\logo_big.jpg" Link="logo_big.jpg" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
