using System;using System.Drawing;using System.Drawing.Imaging;using System.IO;using System.Threading;using System.Threading.Tasks;using Microsoft.Extensions.Logging;using PhotoBooth.Business.Imaging;using PhotoBooth.Core.Models;using PhotoBooth.Core.Services;using PhotoBooth.Infrastructure.Services;using Xunit;
namespace PhotoBooth.UnitTests
{
 public sealed class ProductionServicesTests
 {
  [Fact]public async Task Preset_pipeline_applies_effect_and_writes_300_dpi_png(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);var input=Path.Combine(root,"input.png");var output=Path.Combine(root,"output.png");using(var b=new Bitmap(8,8)){using(var g=Graphics.FromImage(b))g.Clear(Color.FromArgb(80,100,120));b.Save(input,ImageFormat.Png);}var processor=new PresetProcessor(new IImageEffectProcessor[]{new BrightnessProcessor(),new BlackAndWhiteProcessor(),new ResizeProcessor()});var preset=new Preset{SettingsJson="{\"Brightness\":0.2,\"BlackAndWhite\":true,\"OutputWidth\":16,\"OutputHeight\":12,\"Dpi\":300}"};await processor.ProcessAsync(input,preset,output,CancellationToken.None);using(var result=new Bitmap(output)){Assert.Equal(16,result.Width);Assert.Equal(12,result.Height);var c=result.GetPixel(0,0);Assert.Equal(c.R,c.G);Assert.Equal(c.G,c.B);}Directory.Delete(root,true);}
  [Fact]public async Task Print_queue_processes_multiple_jobs(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var printer=new FakePrinter();using(var queue=new PrintQueueService(printer,new TestLogger<PrintQueueService>(),new PhotoBooth.Shared.ApplicationOptions{DataDirectory=root})){await queue.EnqueueAsync(new PrintJob{Id=Guid.NewGuid()},CancellationToken.None);await queue.EnqueueAsync(new PrintJob{Id=Guid.NewGuid()},CancellationToken.None);var limit=DateTime.UtcNow.AddSeconds(3);while(printer.Count<2&&DateTime.UtcNow<limit)await Task.Delay(20);Assert.Equal(2,printer.Count);}Directory.Delete(root,true);}
  [Fact]public void Password_hash_is_salted_and_verifiable(){var service=new PasswordService();var first=service.Hash("1~6");var second=service.Hash("1~6");Assert.NotEqual(first,second);Assert.True(service.Verify("1~6",first));Assert.False(service.Verify("wrong",first));}
  [Fact]public async Task Qr_service_returns_png(){var bytes=await new QrCodeService().GeneratePngAsync(new Uri("https://example.test/photo/1"),240,CancellationToken.None);Assert.True(bytes.Length>100);Assert.Equal(0x89,bytes[0]);Assert.Equal(0x50,bytes[1]);}
  [Fact]public async Task Recovery_does_not_connect_camera_automatically(){var camera=new FakeCamera();var live=new FakeLive();using(var recovery=new RecoveryService(camera,live,new TestLogger<RecoveryService>())){await recovery.StartAsync(CancellationToken.None);await Task.Delay(100);await recovery.StopAsync(CancellationToken.None);Assert.Equal(0,camera.Connects);Assert.Equal(0,live.Starts);}}
  [Fact]public async Task Video_feature_requires_the_module_and_native_encoder(){var options=new PhotoBooth.Shared.ApplicationOptions();var service=new FeatureFlagService(options,new FakeSettings());Assert.True(await service.IsEnabledAsync("Video",CancellationToken.None));options.Features["VideoNativeEncoder"]=false;Assert.False(await service.IsEnabledAsync("Video",CancellationToken.None));options.Features["VideoNativeEncoder"]=true;options.Features["Video"]=false;Assert.False(await service.IsEnabledAsync("Video",CancellationToken.None));}
  [Fact]public async Task Backup_exports_and_restores_application_data(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var backup=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N")+".zip");Directory.CreateDirectory(root);File.WriteAllText(Path.Combine(root,"photobooth.db"),"database");var service=new BackupService(new PhotoBooth.Shared.ApplicationOptions{DataDirectory=root});await service.ExportAsync(backup,CancellationToken.None);File.Delete(Path.Combine(root,"photobooth.db"));await service.ImportAsync(backup,CancellationToken.None);Assert.Equal("database",File.ReadAllText(Path.Combine(root,"photobooth.db")));Directory.Delete(root,true);File.Delete(backup);}
  sealed class FakePrinter:IPrinterService{int count;public int Count=>count;public Task PrintAsync(PrintJob job,CancellationToken token){Interlocked.Increment(ref count);return Task.CompletedTask;}public Task<System.Collections.Generic.IReadOnlyList<string>> GetPrintersAsync(CancellationToken t)=>Task.FromResult<System.Collections.Generic.IReadOnlyList<string>>(new[]{"Mock"});public Task<System.Collections.Generic.IReadOnlyList<DiscoveredPrinter>> ScanAsync(CancellationToken t)=>Task.FromResult<System.Collections.Generic.IReadOnlyList<DiscoveredPrinter>>(new[]{new DiscoveredPrinter{Id="mock",Name="Mock",IsOnline=true}});public async Task<DiscoveredPrinter> ConnectAsync(string id,CancellationToken t)=>(await ScanAsync(t))[0];public Task<bool> IsConnectedAsync(string id,CancellationToken t)=>Task.FromResult(id=="mock");public Task<System.Collections.Generic.IReadOnlyList<PrinterProfile>> GetProfilesAsync(CancellationToken t)=>Task.FromResult<System.Collections.Generic.IReadOnlyList<PrinterProfile>>(new PrinterProfile[0]);public Task SaveProfileAsync(PrinterProfile p,CancellationToken t)=>Task.CompletedTask;public Task DeleteProfileAsync(Guid id,CancellationToken t)=>Task.CompletedTask;}
  sealed class FakeCamera:ICameraService{bool connected;public int Connects;public event EventHandler CamerasChanged;public Task ConnectAsync(CancellationToken t){connected=true;Connects++;return Task.CompletedTask;}public Task ConnectAsync(string id,CancellationToken t)=>ConnectAsync(t);public Task DisconnectAsync(CancellationToken t){connected=false;return Task.CompletedTask;}public Task<System.Collections.Generic.IReadOnlyList<PhotoBooth.Core.Cameras.CameraInfo>> ScanAsync(CancellationToken t)=>GetCamerasAsync(t);public Task<System.Collections.Generic.IReadOnlyList<PhotoBooth.Core.Cameras.CameraInfo>> GetCamerasAsync(CancellationToken t)=>Task.FromResult<System.Collections.Generic.IReadOnlyList<PhotoBooth.Core.Cameras.CameraInfo>>(connected?new[]{new PhotoBooth.Core.Cameras.CameraInfo("mock","Mock",true,"Mock",100,true)}:new PhotoBooth.Core.Cameras.CameraInfo[0]);public Task<PhotoBooth.Core.Cameras.CameraProperties> GetPropertiesAsync(string id,CancellationToken t)=>Task.FromResult<PhotoBooth.Core.Cameras.CameraProperties>(null);public Task SetPropertyAsync(string id,PhotoBooth.Core.Cameras.CameraPropertyKind p,string v,CancellationToken t)=>Task.CompletedTask;public Task<PhotoBooth.Core.Cameras.CaptureResult> CaptureAsync(string id,bool focus,CancellationToken t)=>Task.FromResult<PhotoBooth.Core.Cameras.CaptureResult>(null);public Task<PhotoBooth.Core.Cameras.CaptureResult> CaptureAsync(string id,bool focus,string destination,CancellationToken t)=>CaptureAsync(id,focus,t);public Task<PhotoBooth.Core.Cameras.CaptureResult> CaptureAsync(string id,bool focus,string destination,PhotoBooth.Core.Cameras.CameraSaveMode mode,CancellationToken t)=>CaptureAsync(id,focus,t);}
  sealed class FakeLive:ILiveViewService{public int Starts;public Task StartAsync(string id,CancellationToken t){Starts++;return Task.CompletedTask;}public Task StopAsync(string id,CancellationToken t)=>Task.CompletedTask;public Task FocusAsync(string id,int x,int y,CancellationToken t)=>Task.CompletedTask;public Task<PhotoBooth.Core.Cameras.LiveViewFrame> GetFrameAsync(string id,CancellationToken t)=>Task.FromResult<PhotoBooth.Core.Cameras.LiveViewFrame>(null);}
  sealed class FakeSettings:ISettingsService{public Task<Settings> GetAsync(CancellationToken token)=>Task.FromResult(new Settings());public Task SaveAsync(Settings value,CancellationToken token)=>Task.CompletedTask;}
  sealed class TestLogger<T>:ILogger<T>{public IDisposable BeginScope<TState>(TState state)=>new Scope();public bool IsEnabled(LogLevel level)=>true;public void Log<TState>(LogLevel level,EventId id,TState state,Exception error,Func<TState,Exception,string> formatter){}sealed class Scope:IDisposable{public void Dispose(){}}}
 }
}
