<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Library</OutputType><TargetFramework>net48</TargetFramework><LangVersion>latest</LangVersion><UseWPF>true</UseWPF><PlatformTarget>x86</PlatformTarget><Prefer32Bit>true</Prefer32Bit><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType></PropertyGroup>
  <ItemGroup><ApplicationDefinition Remove="App.xaml" /><Compile Remove="App.xaml.cs" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PhotoBooth.Core\PhotoBooth.Core.csproj" />
    <ProjectReference Include="..\PhotoBooth.Color.D3D11\PhotoBooth.Color.D3D11.csproj" />
    <ProjectReference Include="..\PhotoBooth.Infrastructure\PhotoBooth.Infrastructure.csproj" />
    <ProjectReference Include="..\PhotoBooth.Shared\PhotoBooth.Shared.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
    <Reference Include="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\fox-logo.png" />
    <Resource Include="Assets\photobooth.ico" />
    <Content Include="..\PhotoBooth.Native\Canon\EDSDK.dll" Link="EDSDK.dll" CopyToOutputDirectory="Always" />
    <Content Include="..\PhotoBooth.Native\Canon\EdsImage.dll" Link="EdsImage.dll" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Sounds\*.mp3" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
