using System;using System.Linq;using System.Threading;using System.Windows;using System.Windows.Input;using System.Windows.Threading;using Microsoft.Extensions.DependencyInjection;using PhotoBooth.Core.Services;using PhotoBooth.Customer.UI.Mvvm;using PhotoBooth.Customer.UI.Workflow;
namespace PhotoBooth.Customer.UI.ViewModels
{
 public sealed class CustomerShellViewModel:ObservableObject
 {
  readonly IServiceProvider provider;readonly CustomerWorkflowStateMachine machine;readonly PrinterConnectionViewModel printer;readonly WaitingViewModel waiting;readonly ISettingsService settings;readonly DispatcherTimer idleTimer;object current;bool kiosk=true,cameraStarted,reconnecting;int waitingTimeoutSeconds=30;DateTime lastInteractionUtc=DateTime.UtcNow;bool returningToWaiting;
  public CustomerShellViewModel(IServiceProvider provider,CustomerWorkflowStateMachine machine,PrinterConnectionViewModel printer,ISettingsService settings,WaitingViewModel waiting){this.provider=provider;this.machine=machine;this.printer=printer;this.settings=settings;this.waiting=waiting;CloseCommand=new RelayCommand(()=>{foreach(Window window in Application.Current.Windows)if(window is MainWindow)window.Close();});printer.Completed+=PrinterCompleted;provider.GetRequiredService<FrameSelectionViewModel>().PrinterConnectionRequired+=RequirePrinter;provider.GetRequiredService<CompleteViewModel>().Completed+=async(s,e)=>await ShowWaitingAsync(false);machine.StateChanged+=(s,e)=>{RegisterInteraction();Application.Current.Dispatcher.BeginInvoke(new Action(UpdatePage));};waiting.EnterRequested+=(s,e)=>EnterStart();idleTimer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(1)};idleTimer.Tick+=IdleTick;idleTimer.Start();CurrentPage=printer;_=LoadSettings();}
  public object CurrentPage{get=>current;private set=>Set(ref current,value);}public bool IsKiosk{get=>kiosk;private set=>Set(ref kiosk,value);}public ICommand CloseCommand{get;}
  public void ResetForNewSession(){machine.ResetToIdleQuiet();provider.GetRequiredService<CustomerWorkflowContext>().ResetForNewSession();cameraStarted=false;reconnecting=false;returningToWaiting=false;lastInteractionUtc=DateTime.UtcNow;CurrentPage=printer;}
  public async System.Threading.Tasks.Task ActivateAsync(){await LoadSettings();if(cameraStarted)await provider.GetRequiredService<CaptureViewModel>().ActivateAsync();}
  public void RegisterInteraction(){lastInteractionUtc=DateTime.UtcNow;}
  async System.Threading.Tasks.Task LoadSettings(){var value=await settings.GetAsync(CancellationToken.None);IsKiosk=value?.KioskMode??true;waitingTimeoutSeconds=NormalizeWaitingTimeout(value?.WaitingTimeoutSeconds??30);}
  async void PrinterCompleted(object sender,EventArgs e){if(!cameraStarted){cameraStarted=true;var capture=provider.GetRequiredService<CaptureViewModel>();await capture.ActivateAsync();await ShowWaitingAsync(false);}else{reconnecting=false;CurrentPage=provider.GetRequiredService<FrameSelectionViewModel>();}}
  async void RequirePrinter(object sender,string reason){reconnecting=true;CurrentPage=printer;await printer.RequireConnectionAsync(reason);}
  void EnterStart(){RegisterInteraction();CurrentPage=provider.GetRequiredService<CaptureViewModel>();}
  async void IdleTick(object sender,EventArgs e){if(returningToWaiting||CurrentPage==waiting||reconnecting||!cameraStarted)return;if((DateTime.UtcNow-lastInteractionUtc).TotalSeconds<waitingTimeoutSeconds)return;var state=machine.State;if(state==CustomerWorkflowState.Countdown||state==CustomerWorkflowState.Smile||state==CustomerWorkflowState.Capturing||state==CustomerWorkflowState.InterShotDelay||state==CustomerWorkflowState.Printing||state==CustomerWorkflowState.Complete)return;await ShowWaitingAsync(true);}
  async System.Threading.Tasks.Task ShowWaitingAsync(bool reset){if(returningToWaiting)return;returningToWaiting=true;try{if(reset)await provider.GetRequiredService<CaptureViewModel>().ResetToStartAsync();await waiting.ActivateAsync();CurrentPage=waiting;lastInteractionUtc=DateTime.UtcNow;}finally{returningToWaiting=false;}}
  void UpdatePage(){if(reconnecting||CurrentPage==waiting)return;if(machine.State==CustomerWorkflowState.FrameSelection){CurrentPage=provider.GetRequiredService<FrameSelectionViewModel>();return;}if(machine.State==CustomerWorkflowState.VideoSelection||machine.State==CustomerWorkflowState.Printing){CurrentPage=provider.GetRequiredService<VideoSelectionViewModel>();return;}if(machine.State==CustomerWorkflowState.Complete){CurrentPage=provider.GetRequiredService<CompleteViewModel>();return;}CurrentPage=provider.GetRequiredService<CaptureViewModel>();}
  static int NormalizeWaitingTimeout(int seconds)=>seconds==60||seconds==120||seconds==300||seconds==600||seconds==900?seconds:30;
 }
}
