using System;using System.Collections.ObjectModel;using System.IO;using System.Linq;using System.Threading;using System.Threading.Tasks;using System.Windows.Input;using Microsoft.Extensions.Logging;using PhotoBooth.Core.Models;using PhotoBooth.Core.Pipelines;using PhotoBooth.Core.Services;using PhotoBooth.Customer.UI.Mvvm;using PhotoBooth.Customer.UI.Workflow;
namespace PhotoBooth.Customer.UI.ViewModels
{
 public sealed class FrameSelectionViewModel:ObservableObject
 {
  readonly CustomerWorkflowStateMachine machine;readonly CustomerWorkflowContext context;readonly IFrameService frames;readonly IPresetService presets;readonly IPrinterService printers;readonly IImageCompositionService composer;readonly IPresetProcessor presetProcessor;readonly IStorageManager storage;readonly ISessionService sessions;readonly ICaptureService captures;readonly IGifAnimationService gifAnimation;readonly IPrintPipeline printPipeline;readonly ILogger<FrameSelectionViewModel> log;Frame selected;string preview,error;bool printing;
  public FrameSelectionViewModel(CustomerWorkflowStateMachine m,CustomerWorkflowContext c,IFrameService f,IPresetService p,IPrinterService printer,IImageCompositionService compose,IPresetProcessor processor,IStorageManager storageManager,ISessionService session,ICaptureService captureService,IGifAnimationService gifService,IPrintPipeline pipeline,ILogger<FrameSelectionViewModel> logger){machine=m;context=c;frames=f;presets=p;printers=printer;composer=compose;presetProcessor=processor;storage=storageManager;sessions=session;captures=captureService;gifAnimation=gifService;printPipeline=pipeline;log=logger;CancelCommand=new RelayCommand(()=>machine.MoveTo(CustomerWorkflowState.Preview));PrintCommand=new AsyncCommand(Print,()=>SelectedFrame!=null&&!IsPrinting);RetryCommand=new AsyncCommand(Print);CancelErrorCommand=new RelayCommand(()=>ErrorMessage=null);machine.StateChanged+=(s,e)=>{if(machine.State==CustomerWorkflowState.FrameSelection)_=Load();};}
  public event EventHandler<string> PrinterConnectionRequired;public ObservableCollection<Frame> PinnedFrames{get;}=new ObservableCollection<Frame>();public Frame SelectedFrame{get=>selected;set{if(Set(ref selected,value)&&value!=null){context.SelectedFrame=value;_=UpdatePreview();}}}public string PreviewPath{get=>preview;private set=>Set(ref preview,value);}public string ErrorMessage{get=>error;private set{Set(ref error,value);Raise(nameof(HasError));}}public bool HasError=>!string.IsNullOrWhiteSpace(ErrorMessage);public bool IsPrinting{get=>printing;private set=>Set(ref printing,value);}public ICommand CancelCommand{get;}public ICommand PrintCommand{get;}public ICommand RetryCommand{get;}public ICommand CancelErrorCommand{get;}
  async Task Load(){try{ErrorMessage=null;PinnedFrames.Clear();var usable=(await frames.GetAllAsync(CancellationToken.None)).Where(x=>x.Slots!=null&&x.Slots.Count>0&&x.PixelWidth>0&&x.PixelHeight>0&&!string.IsNullOrWhiteSpace(x.SourcePath)&&File.Exists(x.SourcePath)).OrderByDescending(x=>x.CreatedAtUtc).ToList();var values=usable.Where(x=>x.IsPinned).Take(10).ToList();if(values.Count==0&&usable.Count>0)values.Add(usable[0]);foreach(var x in values)PinnedFrames.Add(x);if(values.Count==0){ErrorMessage="No usable frame was found. Re-import a frame in Admin.";return;}SelectedFrame=context.Settings?.DefaultFrameId.HasValue==true?values.FirstOrDefault(x=>x.Id==context.Settings.DefaultFrameId.Value)??values[0]:values[0];}catch(Exception e){Fail(e,"Frame unavailable");}}
  async Task UpdatePreview(){try{ErrorMessage=null;await Compose(false);}catch(Exception e){Fail(e,"Frame preview could not be generated");}}
  async Task Compose(bool final)
  {
   if(context.Session==null||SelectedFrame==null)return;
   var all=await presets.GetAllAsync(CancellationToken.None);
   context.DefaultPreset=context.Settings?.DefaultPresetId.HasValue==true?all.FirstOrDefault(x=>x.Id==context.Settings.DefaultPresetId.Value):all.FirstOrDefault(x=>x.IsDefault);
   var sourceFiles=(context.CurrentCaptureFiles.Count>0?context.CurrentCaptureFiles:context.Session.CapturedFiles.ToList()).Where(File.Exists).ToList();
   var working=new Session{Id=context.Session.Id,StartedAtUtc=context.Session.StartedAtUtc,OutputDirectory=context.Session.OutputDirectory,SessionNumber=context.Session.SessionNumber,FrameIndex=context.Session.FrameIndex,CapturedFiles=sourceFiles};
   var composed=await composer.ComposeAsync(working,SelectedFrame,context.DefaultPreset,final,CancellationToken.None);
   if(final){context.Session.FrameIndex=working.FrameIndex;context.Session.FinalImageId=working.FinalImageId;}
   if(final&&context.DefaultPreset!=null){var temp=Path.Combine(storage.GetPath("Temp"),Guid.NewGuid().ToString("N")+".png");await presetProcessor.ProcessAsync(composed,context.DefaultPreset,temp,CancellationToken.None);await Task.Run(()=>{File.Copy(temp,composed,true);File.Delete(temp);});}
   PreviewPath=composed;context.Session.FinalImagePath=PreviewPath;await sessions.UpdateAsync(context.Session,CancellationToken.None);
   if(final&&string.IsNullOrWhiteSpace(context.CaptureId)){var retentionDays=context.Settings?.SessionRetentionDays??30;var expires=retentionDays>0?(DateTime?)DateTime.UtcNow.AddDays(retentionDays):null;var capture=await captures.CreateAsync(context.Session.Id,SelectedFrame.Id,context.Session.FinalImageId,composed,sourceFiles,expires,CancellationToken.None);context.CaptureId=capture.Id;}
   if(final)await CreateCaptureGif(sourceFiles);
   log.LogInformation("Frame selected {Frame} ({ImageId}, capture {CaptureId}, originals {OriginalCount})",SelectedFrame.Name,context.Session.FinalImageId,context.CaptureId,sourceFiles.Count);
  }
  Task CreateCaptureGif(System.Collections.Generic.IReadOnlyList<string> sourceFiles){return Task.CompletedTask;}
  async Task Print(){try{ErrorMessage=null;IsPrinting=true;machine.MoveTo(CustomerWorkflowState.Printing);await Compose(true);if(context.PrintingEnabled){var profiles=await printers.GetProfilesAsync(CancellationToken.None);var profile=profiles.SingleOrDefault(x=>x.IsDefault);if(profile==null||!string.Equals(profile.PrinterId,context.ConnectedPrinterId,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Default printer changed. Reconnect the printer.");log.LogInformation("Print queued to {Printer}",profile.PrinterName);await printPipeline.ExecuteAsync(context.Session.Id,profile.Id,CancellationToken.None);}machine.MoveTo(CustomerWorkflowState.Complete);}catch(Exception e){Fail(e,e.Message.IndexOf("printer",StringComparison.OrdinalIgnoreCase)>=0?"Máy in mất kết nối. Vui lòng kết nối lại.":"Printing failed");if(machine.State==CustomerWorkflowState.Printing)machine.MoveTo(CustomerWorkflowState.FrameSelection);if(e.Message.IndexOf("printer",StringComparison.OrdinalIgnoreCase)>=0)PrinterConnectionRequired?.Invoke(this,"Không thể in bằng máy in mặc định. Hãy bật hoặc kết nối lại đúng máy in.");}finally{IsPrinting=false;}}
   void Fail(Exception e,string text){log.LogError(e,text);ErrorMessage=text;}
  }
}
