using System; using System.Collections.Generic; using System.Linq; using System.Threading; using System.Threading.Tasks; using PhotoBooth.Core.Models; using PhotoBooth.Core.Persistence;
namespace PhotoBooth.Business.Repositories
{
 public sealed class InMemoryFrameRepository:IFrameRepository { readonly Dictionary<Guid,Frame> data=new Dictionary<Guid,Frame>(); public Task<Frame> GetAsync(Guid id,CancellationToken t)=>Task.FromResult(data.TryGetValue(id,out var v)?v:null); public Task<IReadOnlyList<Frame>> GetAllAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<Frame>>(data.Values.ToList()); public Task SaveAsync(Frame v,CancellationToken t){data[v.Id]=v;return Task.CompletedTask;} public Task DeleteAsync(Guid id,CancellationToken t){data.Remove(id);return Task.CompletedTask;} }
 public sealed class InMemorySessionRepository:ISessionRepository { readonly Dictionary<Guid,Session> data=new Dictionary<Guid,Session>(); public Task<Session> GetAsync(Guid id,CancellationToken t)=>Task.FromResult(data.TryGetValue(id,out var v)?v:null); public Task<IReadOnlyList<Session>> GetAllAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<Session>>(data.Values.OrderByDescending(x=>x.StartedAtUtc).ToList()); public Task SaveAsync(Session v,CancellationToken t){Project(v);data[v.Id]=v;return Task.CompletedTask;}public Task SetDefaultAsync(Guid id,CancellationToken t){foreach(var x in data.Values)x.IsDefault=x.Id==id;return Task.CompletedTask;}public Task<int> GetNextCaptureSequenceAsync(Guid id,CancellationToken t){if(!data.TryGetValue(id,out var v))throw new InvalidOperationException("Session not found.");v.CaptureIndex++;return Task.FromResult(v.CaptureIndex);}public Task AddCapturedShotAsync(Guid id,CapturedShot shot,CancellationToken t){var v=data[id];v.CapturedShots=(v.CapturedShots??new CapturedShot[0]).Concat(new[]{shot}).OrderBy(x=>x.Sequence).ToList();Project(v);return Task.CompletedTask;}public Task ReplaceCapturedShotAsync(Guid id,string previousShotId,CapturedShot replacement,CancellationToken t){var v=data[id];var shots=(v.CapturedShots??new CapturedShot[0]).ToList();var index=shots.FindIndex(x=>string.Equals(x.Id,previousShotId,StringComparison.Ordinal));if(index<0)throw new InvalidOperationException("Captured shot not found.");shots[index]=replacement;v.CapturedShots=shots.OrderBy(x=>x.Sequence).ToList();Project(v);return Task.CompletedTask;}static void Project(Session v){var shots=(v.CapturedShots??new CapturedShot[0]).OrderBy(x=>x.Sequence).ToList();v.CapturedFiles=shots.Select(x=>x.PicturePath).ToList();v.CapturedMotionFiles=shots.Where(x=>x.HasMotionPhoto).Select(x=>x.MotionPhotoPath).ToList();v.CapturedImageIds=shots.Select(x=>x.Id).ToList();} }
 public sealed class InMemoryPresetRepository:IPresetRepository { readonly Dictionary<Guid,Preset> data=new Dictionary<Guid,Preset>(); public Task<Preset> GetAsync(Guid id,CancellationToken t)=>Task.FromResult(data.TryGetValue(id,out var v)?v:null); public Task<IReadOnlyList<Preset>> GetAllAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<Preset>>(data.Values.ToList()); public Task SaveAsync(Preset v,CancellationToken t){data[v.Id]=v;return Task.CompletedTask;} public Task DeleteAsync(Guid id,CancellationToken t){data.Remove(id);return Task.CompletedTask;} }
 public sealed class InMemoryPrinterProfileRepository:IPrinterProfileRepository { readonly Dictionary<Guid,PrinterProfile> data=new Dictionary<Guid,PrinterProfile>(); public Task<PrinterProfile> GetAsync(Guid id,CancellationToken t)=>Task.FromResult(data.TryGetValue(id,out var v)?v:null);public Task<PrinterProfile> GetByPrinterIdAsync(string id,CancellationToken t)=>Task.FromResult(data.Values.FirstOrDefault(x=>string.Equals(x.PrinterId,id,StringComparison.OrdinalIgnoreCase)));public Task<PrinterProfile> GetDefaultAsync(CancellationToken t)=>Task.FromResult(data.Values.SingleOrDefault(x=>x.IsDefault)); public Task<IReadOnlyList<PrinterProfile>> GetAllAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<PrinterProfile>>(data.Values.ToList()); public Task SaveAsync(PrinterProfile v,CancellationToken t){if(v.IsDefault)foreach(var x in data.Values)x.IsDefault=false;data[v.Id]=v;return Task.CompletedTask;} public Task DeleteAsync(Guid id,CancellationToken t){data.Remove(id);return Task.CompletedTask;} }
 public sealed class InMemorySettingsRepository:ISettingsRepository { Settings value=new Settings(); public Task<Settings> GetAsync(CancellationToken t)=>Task.FromResult(value); public Task SaveAsync(Settings v,CancellationToken t){value=v;return Task.CompletedTask;} }
}
