using System; using System.Collections.Generic; using System.Linq; using System.Threading; using System.Threading.Tasks; using PhotoBooth.Core.Models; using PhotoBooth.Core.Persistence;
namespace PhotoBooth.Business.Repositories
{
 public sealed class InMemoryFrameRepository:IFrameRepository { readonly Dictionary<Guid,Frame> data=new Dictionary<Guid,Frame>(); public Task<Frame> GetAsync(Guid id,CancellationToken t)=>Task.FromResult(data.TryGetValue(id,out var v)?v:null); public Task<IReadOnlyList<Frame>> GetAllAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<Frame>>(data.Values.ToList()); public Task SaveAsync(Frame v,CancellationToken t){data[v.Id]=v;return Task.CompletedTask;} public Task DeleteAsync(Guid id,CancellationToken t){data.Remove(id);return Task.CompletedTask;} }
 public sealed class InMemorySessionRepository:ISessionRepository { readonly Dictionary<Guid,Session> data=new Dictionary<Guid,Session>(); public Task<Session> GetAsync(Guid id,CancellationToken t)=>Task.FromResult(data.TryGetValue(id,out var v)?v:null); public Task<IReadOnlyList<Session>> GetAllAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<Session>>(data.Values.OrderByDescending(x=>x.StartedAtUtc).ToList()); public Task SaveAsync(Session v,CancellationToken t){data[v.Id]=v;return Task.CompletedTask;}public Task SetDefaultAsync(Guid id,CancellationToken t){foreach(var x in data.Values)x.IsDefault=x.Id==id;return Task.CompletedTask;}public Task<int> GetNextCaptureSequenceAsync(Guid id,CancellationToken t){if(!data.TryGetValue(id,out var v))throw new InvalidOperationException("Session not found.");v.CaptureIndex++;return Task.FromResult(v.CaptureIndex);}public Task AddCapturedImageAsync(Guid id,int sequence,string imageId,string filePath,CancellationToken t){var v=data[id];v.CapturedFiles=(v.CapturedFiles??new string[0]).Concat(new[]{filePath}).ToList();v.CapturedImageIds=(v.CapturedImageIds??new string[0]).Concat(new[]{imageId}).ToList();return Task.CompletedTask;} }
 public sealed class InMemoryPresetRepository:IPresetRepository { readonly Dictionary<Guid,Preset> data=new Dictionary<Guid,Preset>(); public Task<Preset> GetAsync(Guid id,CancellationToken t)=>Task.FromResult(data.TryGetValue(id,out var v)?v:null); public Task<IReadOnlyList<Preset>> GetAllAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<Preset>>(data.Values.ToList()); public Task SaveAsync(Preset v,CancellationToken t){data[v.Id]=v;return Task.CompletedTask;} public Task DeleteAsync(Guid id,CancellationToken t){data.Remove(id);return Task.CompletedTask;} }
 public sealed class InMemoryPrinterProfileRepository:IPrinterProfileRepository { readonly Dictionary<Guid,PrinterProfile> data=new Dictionary<Guid,PrinterProfile>(); public Task<PrinterProfile> GetAsync(Guid id,CancellationToken t)=>Task.FromResult(data.TryGetValue(id,out var v)?v:null);public Task<PrinterProfile> GetByPrinterIdAsync(string id,CancellationToken t)=>Task.FromResult(data.Values.FirstOrDefault(x=>string.Equals(x.PrinterId,id,StringComparison.OrdinalIgnoreCase)));public Task<PrinterProfile> GetDefaultAsync(CancellationToken t)=>Task.FromResult(data.Values.SingleOrDefault(x=>x.IsDefault)); public Task<IReadOnlyList<PrinterProfile>> GetAllAsync(CancellationToken t)=>Task.FromResult<IReadOnlyList<PrinterProfile>>(data.Values.ToList()); public Task SaveAsync(PrinterProfile v,CancellationToken t){if(v.IsDefault)foreach(var x in data.Values)x.IsDefault=false;data[v.Id]=v;return Task.CompletedTask;} public Task DeleteAsync(Guid id,CancellationToken t){data.Remove(id);return Task.CompletedTask;} }
 public sealed class InMemorySettingsRepository:ISettingsRepository { Settings value=new Settings(); public Task<Settings> GetAsync(CancellationToken t)=>Task.FromResult(value); public Task SaveAsync(Settings v,CancellationToken t){value=v;return Task.CompletedTask;} }
}
