<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <AssemblyName>CameraControl.Devices</AssemblyName>
    <RootNamespace>CameraControl.Devices</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Interop.WIA">
      <HintPath>..\refs\Interop.WIA.dll</HintPath>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </Reference>
    <Reference Include="System.Management" />
    <Reference Include="System.Net.Http" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Canon.Eos.Framework\Canon.Eos.Framework.csproj" />
    <ProjectReference Include="..\PortableDeviceLib\PortableDeviceLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Accord" Version="3.8.2-alpha" />
    <PackageReference Include="Accord.Video" Version="3.8.2-alpha" />
    <PackageReference Include="Accord.Video.DirectShow" Version="3.8.2-alpha" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.22621.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Rssdp" Version="2.0.9" />
    <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" />
  </ItemGroup>
</Project>
